import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  centerTap: {
    position: 'absolute',
    top: '35%',
    bottom: '35%',
    left: '25%',
    right: '25%',
    zIndex: 999,
    backgroundColor: 'transparent',
  },
  pdf: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  topContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 15,
    paddingTop: 34,
    paddingBottom: 20,
    backgroundColor: 'darkgray',
  },
  topTitle: {
    color: 'white',
    fontSize: 23,
    fontWeight: '600',
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    padding: 6,
    paddingVertical: 10,
    backgroundColor: 'darkgray',
  },
  buttonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 46,
    backgroundColor: 'white',
  },
});
